### ISSUE TITLE
maybe you need maven to manage the dependencies

### ISSUE THREAD

**Issue by gaocegege** [StormSpirit22/zhihu-spider#3]
lib is too large...

**Comment by StormSpirit22** [comment]
You are right, I will check it, thanks~

**Comment by gaocegege** [comment]
welcome, I'm interested in spider, too...

**Comment by StormSpirit22** [comment]
I've created a new repository for this project：https://github.com/StormSpirit22/ZhihuSpider.
Thanks^_^
